@echo off
echo 🚀 Iniciando o Trombiny Portal...
echo 📦 Verificando atualizações e dependências (isso pode demorar na primeira vez)...
call npm install
echo 🌐 Abrindo o site...
start http://localhost:3000
call npm run dev
pause
